comments:
    resource: "@CommentsBundle/Resources/config/routing.yml"
    prefix:   /

events:
    resource: "@EventsBundle/Resources/config/routing.yml"
    prefix:   /

main:
    resource: "@MainBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@MainBundle/Controller/'
    type: annotation
